# -*- coding: utf-8 -*-
"""ABAP-F.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBmNSNM5_4DQe-6oFaiK8zMQcqCVAMgh
"""

import streamlit as st
import pandas as pd

# Inicializar las tablas vacías en el estado de la sesión
if 'buchungen' not in st.session_state:
    st.session_state['buchungen'] = pd.DataFrame(columns=['BELNR', 'BUKRS', 'GJAHR', 'KONTO', 'Betrag', 'SOLL', 'HABEN'])

if 'catalogo_sat' not in st.session_state:
    st.session_state['catalogo_sat'] = pd.DataFrame(columns=['CUENTA', 'DESCRIPCION', 'TIPO'])

# Función para procesar los comandos ABAP con términos SAP FI
def verarbeite_abap_befehl(befehl):
    befehl = befehl.strip().upper()
    if befehl.startswith("SELECT"):
        teile = befehl.split("FROM")
        felder = teile[0].replace("SELECT", "").strip()
        tabelle = teile[1].strip()

        if tabelle == "BUCHUNGEN":
            if "WHERE" in befehl:
                bedingung = befehl.split("WHERE")[1].strip()
                if "BELNR" in bedingung:
                    belnr = bedingung.split("=")[1].strip().replace("'", "")
                    ergebnis = st.session_state['buchungen'][st.session_state['buchungen']['BELNR'] == belnr]
                elif "BUKRS" in bedingung:
                    bukrs = bedingung.split("=")[1].strip().replace("'", "")
                    ergebnis = st.session_state['buchungen'][st.session_state['buchungen']['BUKRS'] == bukrs]
                elif "GJAHR" in bedingung:
                    gjahr = bedingung.split("=")[1].strip().replace("'", "")
                    ergebnis = st.session_state['buchungen'][st.session_state['buchungen']['GJAHR'] == gjahr]
                elif "KONTO" in bedingung:
                    konto = bedingung.split("=")[1].strip().replace("'", "")
                    ergebnis = st.session_state['buchungen'][st.session_state['buchungen']['KONTO'] == konto]
                else:
                    ergebnis = pd.DataFrame()  # No encuentra el campo en la condición
            else:
                ergebnis = st.session_state['buchungen']  # Si no hay WHERE, devuelve toda la tabla
            return ergebnis

    return pd.DataFrame()  # Si no es un comando SELECT válido

# BAPI Simulada para insertar una póliza en FI
def bapi_acc_document_post(belnr, bukrs, gjahr, kontos, betrags, solls, habens):
    for i in range(len(kontos)):
        new_row = pd.DataFrame({
            'BELNR': [belnr],
            'BUKRS': [bukrs],
            'GJAHR': [gjahr],
            'KONTO': [kontos[i]],
            'Betrag': [betrags[i]],
            'SOLL': [solls[i]],
            'HABEN': [habens[i]]
        })
        st.session_state['buchungen'] = pd.concat([st.session_state['buchungen'], new_row], ignore_index=True)
    return "Documento contable creado exitosamente."

# Menú lateral
menu = st.sidebar.selectbox("Menú", [
    "Inicio", "Módulo de Pólizas", "Consultas (ABAP en FI)"
])

if menu == "Inicio":
    st.title("Bienvenido al Sistema Contable basado en SAP FI")
    st.write("Simulación de manejo de pólizas y consultas en FI.")

elif menu == "Módulo de Pólizas":
    st.title("Registro de Pólizas en SAP FI")

    with st.form(key="add_buchung_form"):
        belnr = st.text_input("BELNR (Número de documento)")
        bukrs = st.text_input("BUKRS (Sociedad)")
        gjahr = st.text_input("GJAHR (Año fiscal)")
        kontos = [st.text_input(f"KONTO {i+1}") for i in range(3)]
        betrags = [st.number_input(f"Betrag {i+1}", min_value=0.0) for i in range(3)]
        solls = [st.number_input(f"SOLL {i+1}", min_value=0.0) for i in range(3)]
        habens = [st.number_input(f"HABEN {i+1}", min_value=0.0) for i in range(3)]
        submit_button = st.form_submit_button(label="Registrar Póliza")

        if submit_button:
            if belnr and bukrs and gjahr and any(kontos):
                mensaje = bapi_acc_document_post(belnr, bukrs, gjahr, kontos, betrags, solls, habens)
                st.success(mensaje)
            else:
                st.warning("Por favor, complete todos los campos.")

elif menu == "Consultas (ABAP en FI)":
    st.title("Ejecutar Comandos ABAP en SAP FI")
    abap_befehl = st.text_area("Ingrese su comando ABAP", "SELECT * FROM BUCHUNGEN WHERE BELNR = '1001'")
    if st.button("Ejecutar Comando ABAP"):
        if abap_befehl:
            ergebnis = verarbeite_abap_befehl(abap_befehl)
            if not ergebnis.empty:
                st.write("### Resultado de la consulta:")
                st.dataframe(ergebnis)
            else:
                st.warning("No se encontraron resultados para la consulta.")